version: "3.4"

services:
  portfolio-app:
    image: portfolio:fpm
    environment:
      PHP_IDE_CONFIG: "serverName=portfolio.test"
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 10000
      PHP_OPCACHE_MEMORY_CONSUMPTION: 128
    external_links:
      - nginx-proxy:portfolio.test
    volumes:
      - ./:/app:cached
    networks:
      - default

  portfolio-nginx:
    image: portfolio:nginx
    environment:
      VIRTUAL_HOST: portfolio.test
      HSTS: "off"
      HTTPS_METHOD: noredirect
      APP_DOMAIN: portfolio portfolio.test movies.portfolio.test
      PHP_FPM_HOST: portfolio-app
    volumes:
      - ./:/app:cached
    depends_on:
      - portfolio-app
    networks:
      - default
      - fuse-net

networks:
  default:
  fuse-net:
    external: true
